"""
Waste Detection Engine (Core Business Logic)
---------------------------------------------
Identifies wasted cloud resources from telemetry using threshold-based rules
that mirror real FinOps practice (e.g. AWS Trusted Advisor / Azure Advisor
"low utilization" checks):

  - Idle compute: an instance is flagged only if it is BOTH (a) low on
    average CPU AND (b) *consistently* low across the observation window.
    Using average alone is fragile — a batch job that spikes once a day
    would wrongly look "idle" on average. Consistency guards against that.

  - Stale storage: a bucket is flagged if it hasn't been accessed in more
    than `stale_days_threshold` days (default 90, a common cold-storage
    lifecycle policy trigger).

Also includes `validate_detection_accuracy`, which checks flagged results
against the hidden `_true_*` ground-truth columns generated by the mock
generator. This is what lets us report real precision/recall/F1 numbers
instead of just asserting the detector "works."
"""

from __future__ import annotations

import pandas as pd

# Industry-standard-style defaults, per project decision
IDLE_MEAN_CPU_THRESHOLD_PCT = 10.0     # flag only if mean CPU below this
IDLE_HOURLY_THRESHOLD_PCT = 15.0       # a hour counts as "idle" if CPU below this
IDLE_CONSISTENCY_THRESHOLD = 0.90      # >=90% of hours must be idle to flag
STALE_STORAGE_DAYS_THRESHOLD = 90


def detect_idle_instances(
    inventory_df: pd.DataFrame,
    util_df: pd.DataFrame,
    mean_threshold: float = IDLE_MEAN_CPU_THRESHOLD_PCT,
    hourly_threshold: float = IDLE_HOURLY_THRESHOLD_PCT,
    consistency_threshold: float = IDLE_CONSISTENCY_THRESHOLD,
) -> pd.DataFrame:
    """
    Returns inventory_df enriched with utilization-derived evidence columns
    and a boolean `is_flagged_idle` column.
    """
    stats = (
        util_df.groupby("instance_id")["cpu_utilization_pct"]
        .agg(
            mean_cpu_pct="mean",
            p95_cpu_pct=lambda s: s.quantile(0.95),
            observed_hours="count",
        )
        .reset_index()
    )

    idle_hour_fraction = (
        util_df.assign(is_idle_hour=util_df["cpu_utilization_pct"] < hourly_threshold)
        .groupby("instance_id")["is_idle_hour"]
        .mean()
        .reset_index()
        .rename(columns={"is_idle_hour": "idle_hour_fraction"})
    )

    stats = stats.merge(idle_hour_fraction, on="instance_id")

    merged = inventory_df.merge(stats, on="instance_id", how="left")

    merged["is_flagged_idle"] = (
        (merged["mean_cpu_pct"] < mean_threshold)
        & (merged["idle_hour_fraction"] >= consistency_threshold)
    )

    return merged


def detect_stale_storage(
    storage_df: pd.DataFrame,
    days_threshold: int = STALE_STORAGE_DAYS_THRESHOLD,
) -> pd.DataFrame:
    """Returns storage_df enriched with an `is_flagged_stale` boolean column."""
    out = storage_df.copy()
    out["is_flagged_stale"] = out["last_accessed_days_ago"] > days_threshold
    return out


def validate_detection_accuracy(
    flagged_df: pd.DataFrame,
    predicted_col: str,
    ground_truth_col: str,
) -> dict:
    """
    Computes precision, recall, F1, and a confusion matrix comparing the
    detector's flags against the synthetic ground truth embedded in the
    mock data. This is only meaningful on synthetic/labeled data — on real
    telemetry there is no ground truth, so this function exists purely to
    validate the detection logic itself during development.
    """
    y_true = flagged_df[ground_truth_col].astype(bool)
    y_pred = flagged_df[predicted_col].astype(bool)

    tp = int(((y_true) & (y_pred)).sum())
    fp = int((~y_true & y_pred).sum())
    fn = int((y_true & ~y_pred).sum())
    tn = int((~y_true & ~y_pred).sum())

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = (
        2 * precision * recall / (precision + recall)
        if (precision + recall) > 0
        else 0.0
    )
    accuracy = (tp + tn) / len(flagged_df) if len(flagged_df) > 0 else 0.0

    return {
        "true_positives": tp,
        "false_positives": fp,
        "false_negatives": fn,
        "true_negatives": tn,
        "precision": round(precision, 4),
        "recall": round(recall, 4),
        "f1_score": round(f1, 4),
        "accuracy": round(accuracy, 4),
    }


if __name__ == "__main__":
    # Quick standalone sanity check against the generated mock data
    inventory = pd.read_csv("data/raw/instance_inventory.csv")
    util = pd.read_csv("data/raw/vm_hourly_utilization.csv")
    storage = pd.read_csv("data/raw/storage_inventory.csv")

    flagged_instances = detect_idle_instances(inventory, util)
    flagged_storage = detect_stale_storage(storage)

    print("=== Idle Instance Detection ===")
    print(
        flagged_instances[
            ["instance_id", "instance_type", "mean_cpu_pct", "idle_hour_fraction", "is_flagged_idle"]
        ].to_string(index=False)
    )

    print("\n=== Detection Accuracy vs Synthetic Ground Truth (Compute) ===")
    metrics = validate_detection_accuracy(flagged_instances, "is_flagged_idle", "_true_is_wasteful")
    for k, v in metrics.items():
        print(f"{k}: {v}")

    print("\n=== Detection Accuracy vs Synthetic Ground Truth (Storage) ===")
    storage_metrics = validate_detection_accuracy(flagged_storage, "is_flagged_stale", "_true_is_stale")
    for k, v in storage_metrics.items():
        print(f"{k}: {v}")
